#-------------------------------------------------
# Database  Settings
#-------------------------------------------------
host: localhost
port: 27017
db_name: sunbeamdb
sent_db: test_sentencedb
ingestion_db: test_rawfeeddb


#-------------------------------------------------
# Merchant-specific data field names
#-------------------------------------------------
merchants:
  Amazon: 
    sku: asin
    review_text: reviewText