#-------------------------------------------------
# Database  Settings
#-------------------------------------------------
host: localhost
port: 27017
db_name: sunbeamdb
sent_db: test_sentencedb
ingestion_db: test_rawfeeddb
jobs_db: test_jobsdb
queue_db: queuedb
status_db: statusdb
details_db: detailsdb



#-------------------------------------------------
# Merchant-specific data field names
#-------------------------------------------------
merchants:
  Amazon: 
    sku: asin
    review_text: reviewText

#-------------------------------------------------
# Doc2Vec parameters/hyperparameters
#-------------------------------------------------
doc2vec:
  vector_size: 100
  epochs: 20
  min_count: 50
  dm: 0
  negative: 5
  alpha: 0.025
  min_alpha: 0.001
  path: ml/models
  inference:
    topn: 10
    steps: 100000

#-------------------------------------------------
# Scraper parameters
#-------------------------------------------------
scraper:
  thread_count: 40
  http_timeout: 3
  sleep_max: 1
  sleep_min: 0
  http_codes:
    success: 200
    fail: 0
  proxies:
    http: http://5.79.73.131:13010
    https: http://5.79.73.131:13010 

misc:
  min_review_count: 50

