version: '3.5'

networks:
  mongonet:
    driver: bridge

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/bitnami
    networks:
      - mongonet
    hostname: mongodb_container
  sunbeam:
    image: 'sunbeam'
    ports:
      - "5000:80"
    networks:
      - mongonet
    hostname: sunbeamapp_container

      
# # version: '3'
# # services:
# #   app:
# #     image: sunbeampy
# #     dockerfile: Dockerfile
# #     build:
# #       context: app
# #     volumes:
# #       - app:/usr/src/app/
# #   frontend:
# #     image: nginx:1.13-alpine
# #     volumes:
# #       - nginx.conf:/etc/nginx/conf.d/default.conf:ro
# #       - app:/usr/share/nginx/html:ro
# #     depends_on:
# #       - app
# #     ports:
# #       - 80:80
# # volumes:
# #   app:
# #   nginx.conf:




# # version: '3.5'
# # services:
# #   sunbeamjs:
# #     container_name: sunbeamjs
# #     build:
# #       context: .
# #       dockerfile: Dockerfile
# #     ports:
# #       - '80:80'


# version: '3.5'
# services:
#   app:
#     image: sunbeampy
#     build:
#       context: .
#       dockerfile: Dockerfile

      
#   #   volumes:
#   #     - ./backend/public:/usr/src/app/public
#   # frontend:
#   #   image: nginx:1.13-alpine
#   #   volumes:
#   #     - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#   #     - ./backend/public:/usr/share/nginx/html:ro
#   #   depends_on:
#   #     - backend
#   #   ports:
#   #     - 80:80

# #  Named volume "nginx.conf:/etc/nginx/conf.d/default.conf:ro" is used in service "frontend" but no declaration was found in the volumes section.