version: '3.5'

networks:
  mongonet:
    driver: bridge
services:
  mongodb:
    container_name: mongodb_container
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - /User/$USER/data/db:/bitnami
    networks:
      - mongonet
    hostname: mongodb_container
  sunbeam:
    container_name: sunbeamflask_container
    image: 'sunbeam'
    ports:
      - "5000:80"
    volumes:
      - /User/$USER/data/sunbeam/ml:/app/ml/models
    networks:
      - mongonet
    hostname: sunbeamapp_container
