version: '3.5'

services:
  mongodb:
    container_name: mongodb_container
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/bitnami
    hostname: mongodb_container
  sunbeam:
    container_name: sunbeamflask_container
    image: 'sunbeam'
    ports:
      - "5000:80"
    volumes:
      - /data/sunbeam/ml:/app/ml/models
    hostname: sunbeamapp_container
