#-------------------------------------------------
# Database  Settings
#-------------------------------------------------
host: localhost
  # host: "mongodb"
port: 27017
sent_db: test_sentencedb
ingestion_db: test_rawfeeddb
queue_db: test_queuedb
status_db: test_statusdb
details_db: test_detailsdb
votes_db: test_votesdb

#-------------------------------------------------
# AWS Tokens
#-------------------------------------------------
aws_access_key_id: AKIAJP7QTUMWN425UFJQ
aws_secret_access_key: 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
s3_directory: "sunbeam"


#-------------------------------------------------
# Merchant-specific data field names
#-------------------------------------------------
merchants:
  Amazon: 
    sku: asin
    review_text: reviewText

#-------------------------------------------------
# Doc2Vec parameters/hyperparameters
#-------------------------------------------------
doc2vec:
  vector_size: 100
  epochs: 20
  min_count: 1
  dm: 0
  negative: 5
  alpha: 0.025
  min_alpha: 0.001
  # path: /ml/models
  path: ml/models
  inference:
    topn: 10
    steps: 100000

#-------------------------------------------------
# Scraper parameters
#-------------------------------------------------
scraper:
  thread_count: 6
  http_timeout: 5
  sleep_max: 5
  sleep_min: 2
  http_codes:
    success: 200
    fail: 0
  proxies:
    http: http://5.79.73.131:13010
    https: http://5.79.73.131:13010 

misc:
  min_review_count: 30
  error_msg: "Unknown Error"
  max_title_length: 90

